apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-v2
  template:
   metadata:
     labels:
       app: nodejs-v2
   spec:
     containers:
     - name: node-container
       image: my-first-server
       imagePullPolicy: IfNotPresent 
       ports:
       - containerPort: 500
 
