apiVersion: v1
kind: Service
metadata:
  name: node-js-service-v2
spec:
  selector:
    app: nodejs-2
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 500
    nodePort: 30002
  type: NodePort 
